### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Cowation** [Cowation/toughcraft#1]
- [x] Update Java CI workflow to only run on updates to master AND only when the src path, **.xml, or **.yml (wildcard) is edited. [Include Path](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths) 
- [x] Create a new release v0.1.0; adding the first ToughCraft command, /toughtoggle. Also edit the jar metadata to display the correct version.
- [x] Create a new branch for new features.
- [x] Stop committing changes to master.
